SecteEcoPlus/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SecteEcoPlus.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }
        /// <summary>
        /// Whether or not the request id should be shown
        /// </summary>
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
        public void OnGet() { }
    }
}

SecteEcoPlus/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SecteEcoPlus.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
            
        }
    }
}

SecteEcoPlus/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SecteEcoPlus.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet() { }
    }
}

SecteEcoPlus/ViewComponents/WebsiteReviewsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using SecteEcoPlus.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static SecteEcoPlus.Cache;
namespace SecteEcoPlus.ViewComponents
{
    public class WebsiteReviewsViewComponent : ViewComponent
    {
        private readonly WebsiteContext _context;
        private readonly IMemoryCache _cache;
        public WebsiteReviewsViewComponent(WebsiteContext context, IMemoryCache cache)
        {
            _context = context;
            _cache = cache;
        }
        public async Task<IViewComponentResult> InvokeAsync(IEnumerable<Message> baseMessages = null)
        {
            var messages = baseMessages?.ToList() ?? await _cache.GetOrCreateAsync(LastReviews, async i =>
            {
                i.SetOptions(new MemoryCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromHours(12)));
                return await _context.WebsiteReviews
                    .AsNoTracking()
                    .Include(m => m.Author)
                    .OrderByDescending(x => x.PublishDate)
                    .Take(10)
                    .ToListAsync();
            });
            return View(messages);
        }
    }
}

SecteEcoPlus/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewBag.Title = "La secte éco+";
    ViewBag.UseJqueryAjax = true;
}
<div>
    <h1>Bienvenue dans la secte éco+</h1>
    <p>La secte vénère les produits éco+ et surtout, les produits Leclerc.</p>
    <p>Nous suivons les recettes sacrées d'El Pueblo, et nous achetons que des produits éco+.</p>
    <p>Rejoins-nous, achète des produits éco+, et sois un véritable leclerien.</p>
    <p class="font-weight-bold"><a asp-page="/Ideas/Index">NOUVEAU : Il est maintenant possible d'envoyer des idées de produits éco+ !</a></p>
    <div class="container mt-3 px-0">
        <div class="row mb-1">
            <div class="col-md-5 col-lg-4">
                <h3 class="my-0">Écrire une suggestion</h3>
            </div>
            <div class="col-md d-none d-md-block">
                <h3 class="my-0">Dernières suggestions</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-5 col-lg-4">
                <cache enabled="true" vary-by-user="true" expires-after="@TimeSpan.FromMinutes(5)" vary-by-query="refresh">
                    <partial name="_WebsiteReviewFormPartial" model="@(new MessageRequestViewModel())" /> @* Send ideas here *@
                </cache>
            </div>
            <div class="col-md reviews">
                <cache enabled="true" expires-after="@TimeSpan.FromSeconds(10)" expires-sliding="@TimeSpan.FromSeconds(20)">
                    @await Component.InvokeAsync("WebsiteReviews")
                </cache>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}