SecteEcoPlus/Controllers/IdeasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.Xml;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.V3.Pages.Internal.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SecteEcoPlus.Areas.Identity;
using SecteEcoPlus.Areas.Identity.Data;
using SecteEcoPlus.Models;

namespace SecteEcoPlus.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class IdeasController : ControllerBase
    {
        private SecteUserManager _userManager;
        private WebsiteContext _context;
        private SignInManager<SecteUser> _signInManager;

        public const int DownvotedExperiencePenalty = 18;
#if DEBUG
        public const int DownvotesUntilRemoval = 2;
#else
        public const int DownvotesUntilRemoval = 6;
#endif
        public const int UpvoteExperienceBonus = 14;
        public const int VoterExperienceBonus = 3;

        public IdeasController(WebsiteContext context, SecteUserManager userManager, SignInManager<SecteUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [HttpPost, Route("upvote/{id}")]
        public async Task<IActionResult> Upvote(int id) => await CreateVote(id, 1);
        [HttpPost, Route("downvote/{id}")]
        public async Task<IActionResult> Downvote(int id) => await CreateVote(id, -1);
       
        private async Task<IActionResult> CreateVote(int id, int direction)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return Unauthorized();
            }

            var profile = await _userManager.GetPublicProfileByUserAsync(User);
            if (profile is null)
            {
                return BadRequest();
            }
            var idea = await _context.ProductIdeas
                .Select(i => new
                {
                    i.Id,
                    Author = profile.PublicProfileId == i.Author.PublicProfileId ? new PublicProfile() : i.Author, // dummy profile to not self vote 
                    ExisitingVote = i.Votes.FirstOrDefault(v => v.IssuerPublicProfileId == profile.PublicProfileId),
                    VoteCount = i.Votes.Sum(v => v.Direction)
                })
                .FirstOrDefaultAsync(i => i.Id == id);
            if (idea is null)
            {
                return NotFound();
            }

            var diff = idea.ExisitingVote != null && idea.ExisitingVote.Direction != direction ? direction * 2 : idea.ExisitingVote != null ? -direction : direction;
            var isFromDownVote = idea.ExisitingVote?.Direction == -1 || idea.ExisitingVote is null && direction == -1;
            _context.Attach(idea.Author);

            if (idea.VoteCount + diff <= -DownvotesUntilRemoval)
            {
                // bad post è_é
                idea.Author.RemoveExperience(DownvotedExperiencePenalty);
                _context.ProductIdeas.Remove(await _context.ProductIdeas.FindAsync(idea.Id));
                goto confirm; // goto bad? no u
            }

            if (idea.ExisitingVote != null)
            {
                if (!TryReplaceExistingVote(direction, idea.ExisitingVote))
                {
                    profile.ExperienceDebt += VoterExperienceBonus;
                }
            }
            else
            {
                await InsertNewVoteAsync(direction, profile, idea.Id);
                profile.AddExperience(VoterExperienceBonus);
            }
            ProcessExperience(diff, idea.Author, isFromDownVote);

            confirm:
            await _context.SaveChangesAsync();
            return Ok();
        }
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteIdea(int id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return Unauthorized();
            }

            var idea = await _context.ProductIdeas.FindAsync(id);
            if (idea is null) return NotFound();

            if (idea.AuthorPublicProfileId != await _userManager.GetPublicProfileIdByUserAsync(User))
            {
                return Unauthorized();
            }

            _context.ProductIdeas.Remove(idea);
            await _context.SaveChangesAsync();
            return Ok();
        }
        private static void ProcessExperience(int diff, PublicProfile author, bool isFromDownVote = false)
        {
            if (diff == 0) return;
            var sign = Math.Clamp(diff, -1, 1);
            var downvoteXp = diff * UpvoteExperienceBonus / 4;
            var xp = UpvoteExperienceBonus * sign;
            if (isFromDownVote && diff <= 1) xp = downvoteXp;
            if (diff > 1 || diff < -1) // big vote (upvote -> downvote)
            {
                xp += (downvoteXp / diff) * sign;
            }
            author.AddExperience(xp);
        }
        /// <summary>
        /// Replaces the existing vote, or deletes it if direction == 0
        /// </summary>
        /// <param name="direction">The vote direction</param>
        /// <param name="existingVote">The existing vote</param>
        /// <returns>Whether ot not the vote has been replaced or deleted</returns>
        private bool TryReplaceExistingVote(int direction, ProductIdeaVote existingVote)
        {
            if (existingVote.Direction == direction)
            {
                _context.ProductIdeaVotes.Remove(existingVote);
                return false;
            }
            else
            {
                _context.Attach(existingVote);
                existingVote.Direction = direction;
                return true;
            }
        }

        private async Task InsertNewVoteAsync(int direction, PublicProfile profile, int ideaId)
        {
            var vote = new ProductIdeaVote
            {
                Direction = direction,
                Issuer = profile,
                ProductIdeaId = ideaId
            };
            await _context.ProductIdeaVotes.AddAsync(vote);
        }
    }
}

SecteEcoPlus/Pages/Ideas/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SecteEcoPlus.Areas.Identity;
using SecteEcoPlus.Models;

namespace SecteEcoPlus.Pages.Ideas
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private SecteUserManager _userManager;
        private WebsiteContext _context;

        public CreateModel(SecteUserManager manager, WebsiteContext context)
        {
            _userManager = manager;
            _context = context;
        }
        [BindProperty]
        public InputModel Input { get; set; }
        public class InputModel
        {
            [Required(ErrorMessage = "L'idée est manquante :/")]
            [Display(Name = "Idée de produit", Description = "Décrit le produit que vous voulez concevoir")]
            [StringLength(500, MinimumLength = 4, ErrorMessage = "L'{0} doit être moins longue que {1} caractères et pas trop petite (min {2}) !")]
            public string Content { get; set; }
        }
        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var profile = await _userManager.GetPublicProfileByUserAsync(User);
            if (profile is null)
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }

            var idea = new ProductIdea
            {
                Author = profile,
                Content = Input.Content,
                PublishDate = DateTime.Now
            };
            await _context.ProductIdeas.AddAsync(idea);
            await _context.SaveChangesAsync();
            return RedirectToPage("Index", new { refresh = true });
        }
    }
}

SecteEcoPlus/Pages/Ideas/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SecteEcoPlus.Areas.Identity;
using SecteEcoPlus.Models;
using SecteEcoPlus.ViewModels;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal;
using SecteEcoPlus.Areas.Identity.Data;

namespace SecteEcoPlus.Pages.Ideas
{
    public class IndexModel : PageModel
    {
        public class Love : DynamicObject
        {
            private static readonly string[] Messages = {
                "I love you, my {0}",
                "I love {0}",
                "{0} is my favorite",
                "{0} is the best",
                "I love {0} so much!!!",
                "{0} is my bae",
                "{0} best thing ever",
                "OwO i luv {0} ;3"
            };
            private static readonly Random Random = new Random();
            public override bool TryGetMember(GetMemberBinder binder, out object result)
            {
                result = string.Format(Messages[Random.Next(0, Messages.Length)].Split('_').Aggregate((a, b) => $"{a} {b}"), binder.Name);
                return true;
            }
        }
        private readonly WebsiteContext _context;
        private readonly SecteUserManager _manager;
        private readonly SignInManager<SecteUser> _signInManager;
        public IEnumerable<ProductIdeaItemViewModel> Ideas { get; set; }

        public IndexModel(WebsiteContext context, SecteUserManager manager, SignInManager<SecteUser> signInManager)
        {
            _context = context;
            _manager = manager;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> OnGet()
        {
            var ideas = await GetFeaturedIdeas();
            Ideas = ideas;
            return Page();
        }

        private async Task<IEnumerable<ProductIdeaItemViewModel>> GetFeaturedIdeas()
        {
            var profileId = !_signInManager.IsSignedIn(User) ? null : await _manager.GetPublicProfileIdByUserAsync(User);
            var hasUser = profileId.HasValue;
            var ideas = await _context
                .ProductIdeas
                .AsNoTracking()
                .Select(i => new
                {
                    VM = new ProductIdeaItemViewModel
                    {
                        Id = i.Id,
                        Content = i.Content,
                        Author = new PublicProfileViewModel
                        {
                            DisplayName = i.Author.DisplayName,
                            Id = i.AuthorPublicProfileId
                        },
                        PublishDate = i.PublishDate,
                        TotalVotes = i.Votes.Any() ? i.Votes.Sum(v => v.Direction) : 0, // prevent NULL values
                        IsFromUser = i.AuthorPublicProfileId == profileId
                    },
                    TimeBatch = Math.Floor(EF.Functions.DateDiffHour(i.PublishDate, DateTime.Now) / 25d),
                    CurrentUserVote = i.Votes.Where(v => hasUser && v.IssuerPublicProfileId == profileId).Select(v => v.Direction).ToList()
                })
                .OrderBy(i => i.TimeBatch)
                .ThenByDescending(i => i.VM.TotalVotes)
                .ThenByDescending(i => i.VM.PublishDate).ToListAsync();

            if (!hasUser) return ideas.Select(i => i.VM).ToList();
            foreach (var idea in ideas)
            {
                idea.VM.VoteDirection = idea.CurrentUserVote.FirstOrDefault();
            }

            return ideas.Select(i => i.VM).ToList();
        }
    }
}

SecteEcoPlus/Pages/Ideas/Create.cshtml
@page
@using SecteEcoPlus.Controllers
@model SecteEcoPlus.Pages.Ideas.CreateModel
@{
    ViewBag.Title = "Nouvelle idée";
}

<h1>Nouvelle idée</h1>
<h3>Créez une nouvelle idée de produit éco+ !</h3>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
            <form method="post">
                <textarea asp-for="Input.Content" placeholder="Décrivez ici votre idée de produit pas cher" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Input.Content"></span>
                <input type="submit" class="btn btn-success form-control my-2"/>
            </form>
        </div>
        <div class="col-lg-6">
            <h3>Conseils pour vos idées</h3>
            <p>Mettre des idées permet de rendre la secte active et démontrer son sens de l'imagination.</p>
            <p>Une idée c'est imaginer un nouveau produit éco+, comme un aspirateur éco+ (loul)</p>
            <p>Vous gagnez de l'expérience lorsque quelqu'un vote pour votre idée.</p>
            <p class="text-danger font-weight-bold">Si votre idée est trop mauvaise, elle sera supprimée.</p>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

SecteEcoPlus/Pages/Ideas/Index.cshtml
@page
@model SecteEcoPlus.Pages.Ideas.IndexModel
@{
    ViewBag.Title = "Idées";
    var ideaButton = (new Template(@<a class="btn btn-outline-primary" asp-page="./Create">Ajouter une idée</a>).ToParameterLess());
}
<h1>@ViewBag.Title @ideaButton()</h1>
<h3>Des idées pour de nouveaux produits éco+</h3>
<hr/>
<div class="container-fluid">
    <h4>Idées du moment</h4>
    <div class="row">
        @if (Model.Ideas?.Any() ?? false)
        {
            foreach (var idea in Model.Ideas)
            {
                <div class="col-md-6 col-lg-5 col-xl-4 my-2 idea-container">
                    <partial name="_Idea" model="@idea" />
                </div>
            }
        }
        else
        {
            <div class="container bg-light rounded shadow-lg p-4 my-3 border border-grey">
                <h4>C'est bizarre...</h4>
                <p>On dirait qu'il n'y a pas d'idées ici... Vous pouvez en mettre une si vous voulez !</p>
                @ideaButton()
            </div>
        }
    </div>
</div>
@section Scripts
{
    <script src="~/js/ideas.js"></script>
}

SecteEcoPlus/Pages/Ideas/_Idea.cshtml
@model ProductIdeaItemViewModel
@using SecteEcoPlus.Controllers
<div class="card idea @(Model.TotalVotes <= -2 ? "bad-idea" : "")">
    <div class="card-body">
        @Model.Content
    </div>
    <div class="card-footer small">
        <div class="row">
            <div class="col">
                <div class="d-flex align-items-center h-100 my-auto">
                    <div class="text-muted align-middle">
                        Créée par
                        @Html.DisplayFor(m => m.Author, "ProfileLink")<span class="d-none d-md-inline">,</span><br class="d-block d-md-none" />
                        le @Html.DisplayTextFor(m => m.PublishDate)
                    </div>
                </div>
            </div>
            <div class="col-auto">
                <button class="d-inline btn btn-outline-success btn-sm @(Model.VoteDirection == 1 ? "active" : "") vote"
                        data-vote-url="@Url.Action("Upvote", "Ideas", new {id = Model.Id})" data-upvote>
                    <span class="fa fa-arrow-up"></span>
                </button>
                <span class="votes-count align-middle mx-1">@Model.TotalVotes</span>
                <button class="d-inline btn btn-outline-danger btn-sm @(Model.VoteDirection == -1 ? "active" : "") vote"
                        data-vote-url="@Url.Action("Downvote", "Ideas", new {id = Model.Id})" data-downvote>
                    <span class="fa fa-arrow-down"></span>
                </button>
                @if (Model.IsFromUser)
                {
                <button class="d-inline btn btn-danger btn-sm" data-delete-request-url="@Url.Action("DeleteIdea", "Ideas", new {id = Model.Id})">
                    <span style="display: none;" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    <span class="fa fa-trash text-white"></span>
                </button>
                }
            </div>
        </div>
    </div>
</div>